cxcsds/ciao-webcode

config.dat, publish_all.pl
=> Update configuration code for CIAO 4.11 release

navbar_main.xsl
This is for the navbar, and is rather ugly. The code should be cleaned
up to be less site-specific.
=> Support a "sticky" mode for links in CSC pages

CIAODOC.pm
No idea what is going on - is this an libxml2 change or in the
Perl layer or ...?
=> Hopefully fix entity expansion

config.dat, publish_all.pl
note,ciaorun not in conda builds so removed from config.dat.  Also keep list_see_also at 4.15
=> ciao-4.16 changes

CIAODOC.pm, config.dat, myhtml.xsl, publish_all.pl
- update config file
- add initial support for a lang tag for screen elements
- `publish_all.pl` will now report an error rather than just error out (when processing a file)
=> Prep for CSC 2.1

CIAODOC.pm, publish.pl
We now explicitly check for pygmentize being present before processing a file containing code blocks with a lang tag, and error out with a hopefully useful error message.
We need CSS rules for when the code is styled. The options are to read them in from a single location or to include them in the file being procesed. For now we go with the latter as it is easier to set up, and is easier to handle code style changes due to the pygmentize code changing. However this is still very experimental.
=> Improvements for code[@lang] blocks

faq.xsl
Allow links to a particular faqsection on the index page.
=> faq: allow faqsections to have id's

myhtml.xsl
Add a screen-<lang> class to any lang-specific screen blocks to allow specialization.
=> screen[@lang] add more rules to allow styling

ahelp_index.xsl
I must have changed the number of columns at some point.
Or I can not count.
=> ahelp: fix validation of index tables

myhtml.xsl
Also better handle unknown values
=> lists now except type of 'i' or 'I'

myhtml.xsl
=> Perhaps I shold have called this annotation rather than admonition

myhtml.xsl
Make sure we don't forget about them...
=> myhtml: let the user know if a TODO is found during development

myhtml.xsl
Looks like I messed up the logic.
=> math: better check

config.dat, publish.pl
Each HTML page is passed through the W3C validator, and reports the warnings / errors that are found.
Let's see how this works.
=> add a validator

myhtml.xsl
Should really review the code rather than just make changes each time I find a problem...
=> myhtml: check up on missing id values

cscdb.xsl
I wanted to make it optional (i.e. the user could decide) but it's too annoying for now.
Is this a good idea?
=> drop the navbar from cscdb page

publish.pl
This should stop seeing errors from non-HTML files like
- slug files
- news RSS file
- redirect files
=> validate: try to only validate actual HTML files

publish.pl
=> publish: validate the thread pages

publish.pl
If publish.pl is called with --validate then any HTML validation errors will be noted and the script will error out when all the files have been processed.
This is intended to make it easy to fix these errors.
=> publish: allow failure on validation problems

publish.pl
=> publish: do not error out if validation error by default

dictionary.xsl
The idea is to make this work better with semantic tools\nlike "reader view", but it does not seem to work.
=> dictionary: tweak the markup

faq.xsl
Follow the dictionary changes. Fun with wanting pre blocks in titles...
=> faq: tweak the markup

common.xsl
Should drop these at the source, not at the sink.
=> More black-list of unwanted body attributes

README.md, links.xsl, unused/list_links.xsl
Ensure that threadlink includes index.html in the link, and add a simple test script that helps find issues.
=> Check links
