myhtml.xsl
The current setup does not make it easy to have wide screen blocks,
since they end up making the display too wide. It is not clear to me
if changes in the HTML5 move (or related CSS changes) have made this
happen, or it always did and the "overflow: auto" rule on these were
never being triggered.
As a simple hack, you can now add a wrap="yes" attribute to screen tags
to allow the text to wrap. This is really meant to be a short-term fix,
but I expect it to remain for a while...
=> Basic support for screen blocks that you want to allow to wrap

CIAODOC.pm, common.xsl
A set of links, listing the location of this page within the
hiearachy of the site, in the form
/ site / dir1 / ... / page.html
are created at the top and bottom of the main section of the page,
where each segment (other than page.html) is a link.
The stylesheets need to have something like the following, where the
parent of .breadcrumbs is position: relative.
position: relative;
}
.breadcrumbs {
background: #eeeeee;
font-family: monospace;
font-size: smaller;
margin-right: 1em;
margin-top: 0.5em;
position: absolute;
right: 1em;
}
.breadcrumbs-top {
top: 0.5em;
}
.breadcrumbs-bottom {
bottom: 0.5em;
}
=> If /*/info/breadcrumbs exists then add a "breadcrumb" trail

config.dat, publish.pl
The publishing script now errors out if the banner file is set but has not been created.
The configs for ciao, sherpa, and chips have banner support added, but commented out.
=> Tweak banner support

publish.pl, publish_all.pl
If the file `DO_NOT_PUBLISH` is found in the working directory, or in any parent directory up to the "base" directory for this site (assumed to be `/data/da/Docs/blah/blah-with-version/`) then refuse to publish. This is to allow the easy inclusion of data, scripts, and ancillary information in the publishing area (since we want to keep them with the docs) without fear of copying them to the website.
Excuse my perl, I am writing in too many different languages nowadays...
=> Allow unpublishable directories

config.dat
The location of the "live" site has changed with the transition
to https (as has the URl to use).
Updates by @kglotfelty
=> Update config file for https transition

CIAODOC.pm, common.xsl, extract_notebook.py, notebook.xsl, publish.pl, templates/conf.json, templates/fakehdr.html.j2, templates/index.html.j2
The initial support for IPython notebooks. The idea is that you create a .xml file containing something like the following (here `sherpa-flux.xml`)
```
<?xml version="1.0" encoding="us-ascii" ?>
<notebook>
<info>
<notebook>sherpa-flux.ipynb</notebook>
<title>
<long>CIAO: calculating fluxes with Sherpa</long>
<short>CIAO: Sherpa and fluxes</short>
</title>
<version>4.12</version>
</info>
<text>
<notebook/>
</text>
</notebook>
```
So you can add extra HTML around the notebook element. You need the notebook in the same directory and they should both get published.
=> Add notebook support

myhtml.xsl
I had an errant disable-output-escaping="yes" line when processing the screen output, causing no-end of problems.
=> fix: screen tags were not being properly converted

links.xsl
The idea is to identify those links we want to download something from our site rather than being something that opens the linked text in a (new) tab.
The alternative was to allow the download attribute to be set, but I like the idea of a new XML tag.
=> Add downloadlink

myhtml.xsl
The contents get dislpayed in bold red, and the page will not publish on the live site.
=> add TODO tag to note things to do

myhtml.xsl
This should be handled better but there's existing pages using this so just do it for now. Add a simple check for really-nested sections just in case ...
=> add subsubsection

myhtml.xsl
The way Ihave set up the xi:include handling we often end up including the "item" tag used to hold the contents. As this is so common let's just process the contents of these tags, and let the user know it's done in case something funky is going on (but who's going to track this ...).
=> myhtml: better-handle item tags

config.dat
We will need to make csc2/ a link when this goes live.
The idea is that we have csc2.0/ and csc2.1/ and then csc2/ will point to the "latest" CSC 2 catalog.
=> CSC 2.0 now goes to the csc2.0/ directory

myhtml.xsl
I had decided to add a warning so that we could see if we are skipping a "legitimate" item tag, but it's too noisy, so just skip. I am assuming that missing any valid item tag would lead to HTML validation issues, so we don't need to worry.
=> myhtml: do not poit out processing an item tag

common.xsl, threadindex_common.xsl
Turns out we use synopsis more than I'd planned, and also needed to avoid unwanted attributes from beibg set on the body tag (this latter just fixes the current problem, it would be nice to "do it properly" but that's hard, and HTML5 is a living standard so it's hard to do well).
=> threadindex: improve HTML validation

myhtml.xsl
Since we now validate the HTML output this has become less-important, but still...
=> catch a few stupid typos for tag names

publish.pl
As noted in
https://github.com/cxcsds/ciao-webcode/issues/85
our HTML validation doesn't like the notebook output. This could be a problem on many ends, but for now we just skip the validation (as some of it is definitely from the notebook code and not something we can change).
=> Do not validate HTML generated by the notebook code

config.dat
The old version used the general setup, which currently refers to CSC 2.0 rather than CSC 2.1.
=> Make sure CSC 2.1 uses CSC 2.1 storage

myhtml.xsl
Ideally it would work out which to use, but for now switch to span.
=> myhtml: TODO now wraps a span rather than div around the contents

config.dat
Not entirely sure whether we really care about whether we use the actual URL or the "generic" version here.
=> config: add explicit versions for some CSC 2.1 links

news.xsl
Ensure the feed.xml page has some minor styling for anyone who clicks on the link.
Tweak the HTML output of the news page to use more HTML5 compliant markup (e.g. article rather than div, and wrap a time value in a time element).
=> Add feed styling

bugs.xsl
Several changes
- use section tag for "broad" areas like "Bugs"
- use artical tag for single bug elememt
- switch the summary tag to a h3 element rather than a div which is not ideal, in particular for those summaries which are screen tags
- fix some list handling were there was not an actual list
=> bugs: use HTML5 section/article tags

news.xsl
Fix up the news items so that each entry has
1, a unique anchor
2. hopefully the anchor remains the same on re-publishing with a changed news file
3. switch from http to https
This may cause feed readers to get annoyed as the entries are changed (even the old ones) because of points 1 and 3.
=> Fix news id duplicates

thread_common.xsl
Switch to section rather than div for the overview. This requires a change to the CIAO css file (to use '#overview' rather than 'div#overview').
=> threads: use section for overview section

links.xsl
It had been using index.html, but that's not useful. For those pages that want to use this they can add href="index.html" to the call.
=> cxclink now uses the current page if href is not set.

links.xsl
For thread pages we want cxclink to go to index.html and not thread.html without actually having to document this. So make this happen and add a check to note when it fails.
=> cxclinks: better handling when href is not given

publish.pl
There's no need to fall over if there are multiple CSS blocks; we can just add to the first one, which will hopefully mean we can over-ride settings if need be. Alternatively we could just add our own CSS block to the start of the file but let's not go there just yet.
=> Allow multiple CSS blocks when using pygmentize

faq.xsl, helper.xsl
This allows <css src="../notebook.css"/> lines to be processed.
However, it is not obvious what exactly is going on here, as the changes are *surprising*, to say the least.
I should pay down the technical debt, but I have no time...
=> faq: allow css to be read from a file
